#!/usr/bin/python

import pickle
from urllib2 import urlopen

#s = "http://www.pythonchallenge.com/pc/def/banner.p"

data = pickle.load(urlopen("http://www.pythonchallenge.com/pc/def/banner.p"))
#u = urlopen(s)
#data = u.read()
#data = u.readline()
print data
#text = cPickle.dumps(data)
# or to binary 
#bytes = cPickle.dumps(data,2)
#print text
#redata1 = cPickle.loads(text)
#print redata1
#print bytes

for line in data:
    print("".join([k * v for k, v in line]))

